# .goreleaser.yml
# このファイルはGoReleaserの設定を定義します

# GoReleaser v2を使用することを明記
version: 2

# プロジェクト名を指定
project_name: translate-markdown

# このファイルが古いバージョンのGoReleaserで実行されるのを防ぐ
before:
  hooks:
    - go mod tidy

builds:
  # macOSとLinux向けのビルド設定
  - id: nix
    main: ./cmd/translate-markdown/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
  # Windows向けのビルド設定
  - id: windows
    main: ./cmd/translate-markdown/
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  # macOSとLinux向けのtar.gzアーカイブ設定
  - id: nix
    formats: [ 'tar.gz' ]
    ids:
      - nix
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
  # Windows向けのzipアーカイブ設定
  - id: windows
    formats: [ 'zip' ]
    ids:
      - windows
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

# リリース後の成果物のチェックサムを計算
checksum:
  name_template: 'checksums.txt'

# スナップショット（開発版）リリースの設定
snapshot:
# name_templateは非推奨のため削除。GoReleaserのデフォルトを使用します。

# CHANGELOGの自動生成設定
changelog:
  sort: asc
  filters:
    # feat, fix, refactorなどのコミットメッセージのみをCHANGELOGに含める
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# GitHubリリースの設定
release:
  # GitHubリリースの設定
  github:
  # リポジトリのオーナーと名前（自動で検出されることが多い）
  # owner: your-github-username
  # name: translate-markdown
  # ドラフトとしてリリースを作成するかどうか
  draft: false
